In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.linear_model import SGDClassifier

# SimpleImputer

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
X = np.array([[10,2],[0,4],[5,3],[np.nan,3]])

In [6]:
 imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
 imputer.fit_transform(X)

array([[10.,  2.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

# KNNImputer

In [7]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(X)

array([[10.,  2.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

# MissingIndicator

In [11]:
from sklearn.impute import MissingIndicator
from sklearn.pipeline import make_union

In [9]:
MissingIndicator().fit_transform(X)

array([[False],
       [False],
       [False],
       [ True]])

In [13]:
pipeline = make_union(SimpleImputer(strategy='constant',fill_value=-99),MissingIndicator())

In [14]:
pipeline.fit_transform(X)

array([[ 10.,   2.,   0.],
       [  0.,   4.,   0.],
       [  5.,   3.,   0.],
       [-99.,   3.,   1.]])

# Application 

In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [16]:
data = sns.load_dataset('titanic')
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [17]:
X = data[['pclass','age']]
y = data[['survived']]

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [19]:
model = make_pipeline(KNNImputer(),SGDClassifier())

In [20]:
params = {
    'knnimputer__n_neighbors':np.arange(1,5)
}

In [21]:
grid = GridSearchCV(model,params,cv=5)

In [22]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('knnimputer', KNNImputer()),
                                       ('sgdclassifier', SGDClassifier())]),
             param_grid={'knnimputer__n_neighbors': array([1, 2, 3, 4])})

In [ ]:
grid.best_params_