In [1]:
import numpy as np

In [ ]:
A = np.array([1,2,3])
A.shape

In [ ]:
A.size

In [ ]:
B = np.zeros((3,2))
B

In [ ]:
B.shape

In [ ]:
B.size

In [ ]:
C = np.ones((3,4))

In [ ]:
C

In [ ]:
C.size

In [ ]:
D = np.full((2,4),7)
D

In [ ]:
np.random.seed(0)
E = np.random.randn(3,4)
E

In [ ]:
E

In [ ]:
np.eye(4)

In [ ]:
np.linspace(0,10,5)

In [ ]:
np.arange(0,20,2,dtype = np.float16)

### Manipulation des tableaux

In [31]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [32]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [33]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [34]:
np.hstack((A,B))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [40]:
D = np.vstack((A,B))

In [37]:
np.concatenate((A,B),axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [45]:
D.size
Z = D.reshape((4,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
X = np.array([1,2,3])
X = X.reshape((A.shape[0],1))
X.shape
X = X.squeeze()

In [54]:
X.shape

(3,)

In [56]:
# ravel applatire un tableau a une seule dimension

(12,)

### Teste Spark

In [3]:

# Reason why we have the getOrCreate code
# http://stackoverflow.com/questions/28999332/how-to-access-sparkcontext-in-pyspark-script
sc = SparkContext.getOrCreate()

NameError: name 'SparkContext' is not defined

In [ ]:

import numpy as np

TOTAL = 1000000
dots = sc.parallelize([2.0 * np.random.random(2) - 1.0 for i in range(TOTAL)]).cache()
print("Number of random points:", dots.count())

stats = dots.stats()
print('Mean:', stats.mean())
print('stdev:', stats.stdev())

In [1]:
%matplotlib inline
from operator import itemgetter
from matplotlib import pyplot as plt

plt.figure(figsize = (10, 5))

# Plot 1
plt.subplot(1, 2, 1)
plt.xlim((-1.0, 1.0))
plt.ylim((-1.0, 1.0))

sample = dots.sample(False, 0.01)
X = sample.map(itemgetter(0)).collect()
Y = sample.map(itemgetter(1)).collect()
plt.scatter(X, Y)

# Plot 2
plt.subplot(1, 2, 2)
plt.xlim((-1.0, 1.0))
plt.ylim((-1.0, 1.0))

inCircle = lambda v: np.linalg.norm(v) <= 1.0
dotsIn = sample.filter(inCircle).cache()
dotsOut = sample.filter(lambda v: not inCircle(v)).cache()

# inside circle
Xin = dotsIn.map(itemgetter(0)).collect()
Yin = dotsIn.map(itemgetter(1)).collect()
plt.scatter(Xin, Yin, color = 'r')

# outside circle
Xout = dotsOut.map(itemgetter(0)).collect()
Yout = dotsOut.map(itemgetter(1)).collect()
plt.scatter(Xout, Yout)

NameError: name 'dots' is not defined