In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0,10,[2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

Methodes ndarray

In [4]:
A.sum()

27

In [5]:
A[0].sum()

8

In [6]:
A[1].sum()

19

In [10]:
A.sum(axis=0)

array([ 8,  7, 12])

In [8]:
A.sum(axis=1)

array([ 8, 19])

In [11]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [14]:
A.sum(axis=1).mean()

13.5

In [15]:
A.prod()

0

In [16]:
A.min()

0

In [17]:
A.min(axis=0)

array([3, 0, 3])

In [18]:
#La position du minimum 
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [19]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

Statistique

In [20]:
A.mean()

4.5

In [21]:
A.std()

2.9297326385411577

In [22]:
A.var()

8.583333333333334

In [26]:
# le tableau obtenu est la matrice de correlation de A :les correlation entre les differntes ligne de A
np.corrcoef(A)[0,1]

-0.5636214801906779

In [28]:
# la fonction np.unique nous retourne a la fois un tableau qui contient les entité presente dans notre tableau numpy et le nombre de repetiton
values , counts = np.unique(A , return_counts=True)

In [29]:
values[counts.argsort()]

array([0, 5, 7, 9, 3])

In [30]:
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'value {i} apparait {j}')

value 0 apparait 1
value 5 apparait 1
value 7 apparait 1
value 9 apparait 1
value 3 apparait 2


NAN Corrrections

In [31]:
A = np.random.randn(5,5)
A[0,2] = np.nan
A[4,3] = np.nan
A

array([[-1.42232584,  1.52006949,         nan, -0.13309028, -0.1730696 ],
       [-1.76165167, -0.08767307,  1.36687937,  1.1253141 , -0.35899555],
       [ 1.2206081 , -1.33949555,  0.42837337, -0.12346315,  1.41437719],
       [-0.12405066,  2.00815709,  0.22988654,  0.60489373,  1.62715982],
       [ 1.59456053,  0.23043417, -0.06491034,         nan,  0.59124281]])

In [32]:
A.mean()

nan

In [34]:
np.nanmean(A)

0.3640535041210288

In [35]:
np.nanvar(A)

1.0110860797805787

In [37]:
#avoir le nombre des entité nan
np.isnan(A).sum()

2

In [40]:
result = np.isnan(A).sum()/A.size
print(f'{result} des valeurs sont nulle ')

0.08 des valeurs sont nulle 


In [44]:
# remplacer par 0 toute les valeurs null
A[np.isnan(A)] = 0
A

array([[-1.42232584,  1.52006949,  0.        , -0.13309028, -0.1730696 ],
       [-1.76165167, -0.08767307,  1.36687937,  1.1253141 , -0.35899555],
       [ 1.2206081 , -1.33949555,  0.42837337, -0.12346315,  1.41437719],
       [-0.12405066,  2.00815709,  0.22988654,  0.60489373,  1.62715982],
       [ 1.59456053,  0.23043417, -0.06491034,  0.        ,  0.59124281]])

Algèbre Linéaire

In [47]:
A = np.ones((2,3))
B = np.ones((3,2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
#Transpose la matrice
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
#le produit matricielle entre A et B
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [57]:
A = np.random.randint(0,10,[3,3])
A

array([[3, 6, 7],
       [2, 0, 3],
       [5, 9, 4]])

In [58]:
#le determinant
np.linalg.det(A)


87.0

In [59]:
# l'inverse de la matrice
np.linalg.inv(A)

array([[-0.31034483,  0.44827586,  0.20689655],
       [ 0.08045977, -0.26436782,  0.05747126],
       [ 0.20689655,  0.03448276, -0.13793103]])

In [13]:
import numpy as np
np.random.seed(0)
A = np.random.randint(0,100, [10 ,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [9]:
meanA  = A.mean()

In [8]:
stdA = A.std()

In [14]:
D = (A - A.mean(axis=0))/A.std(axis=0)
D 

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [15]:
D.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [16]:
D.std(axis=0)

array([1., 1., 1., 1., 1.])